export interface KeyOption {
  value: string;
  label: string;
  category: 'function' | 'navigation' | 'editing' | 'modifier' | 'letter' | 'number' | 'numpad' | 'symbol' | 'media';
}

export const KEY_OPTIONS: KeyOption[] = [
  { value: 'Enter', label: 'Enter', category: 'editing' },
  { value: 'Tab', label: 'Tab', category: 'editing' },
  { value: 'Backspace', label: 'Backspace', category: 'editing' },
  { value: 'Delete', label: 'Delete', category: 'editing' },
  { value: 'Insert', label: 'Insert', category: 'editing' },
  { value: 'Escape', label: 'Escape', category: 'function' },
  { value: 'Space', label: 'Space', category: 'editing' },
  { value: 'CapsLock', label: 'CapsLock', category: 'modifier' },
  { value: 'NumLock', label: 'NumLock', category: 'modifier' },
  { value: 'ScrollLock', label: 'ScrollLock', category: 'modifier' },
  { value: 'Pause', label: 'Pause', category: 'function' },
  { value: 'PrintScreen', label: 'PrintScreen', category: 'function' },
  { value: 'ContextMenu', label: 'ContextMenu', category: 'function' },

  { value: 'Shift', label: 'Shift', category: 'modifier' },
  { value: 'ShiftLeft', label: 'Shift (Left)', category: 'modifier' },
  { value: 'ShiftRight', label: 'Shift (Right)', category: 'modifier' },
  { value: 'Control', label: 'Control', category: 'modifier' },
  { value: 'ControlLeft', label: 'Control (Left)', category: 'modifier' },
  { value: 'ControlRight', label: 'Control (Right)', category: 'modifier' },
  { value: 'Alt', label: 'Alt', category: 'modifier' },
  { value: 'AltLeft', label: 'Alt (Left)', category: 'modifier' },
  { value: 'AltRight', label: 'Alt (Right)', category: 'modifier' },
  { value: 'Meta', label: 'Meta/Command', category: 'modifier' },
  { value: 'MetaLeft', label: 'Meta/Command (Left)', category: 'modifier' },
  { value: 'MetaRight', label: 'Meta/Command (Right)', category: 'modifier' },
  { value: 'AltGraph', label: 'AltGraph', category: 'modifier' },

  { value: 'ArrowUp', label: '↑ Arrow Up', category: 'navigation' },
  { value: 'ArrowDown', label: '↓ Arrow Down', category: 'navigation' },
  { value: 'ArrowLeft', label: '← Arrow Left', category: 'navigation' },
  { value: 'ArrowRight', label: '→ Arrow Right', category: 'navigation' },
  { value: 'Home', label: 'Home', category: 'navigation' },
  { value: 'End', label: 'End', category: 'navigation' },
  { value: 'PageUp', label: 'PageUp', category: 'navigation' },
  { value: 'PageDown', label: 'PageDown', category: 'navigation' },

  { value: 'F1', label: 'F1', category: 'function' },
  { value: 'F2', label: 'F2', category: 'function' },
  { value: 'F3', label: 'F3', category: 'function' },
  { value: 'F4', label: 'F4', category: 'function' },
  { value: 'F5', label: 'F5', category: 'function' },
  { value: 'F6', label: 'F6', category: 'function' },
  { value: 'F7', label: 'F7', category: 'function' },
  { value: 'F8', label: 'F8', category: 'function' },
  { value: 'F9', label: 'F9', category: 'function' },
  { value: 'F10', label: 'F10', category: 'function' },
  { value: 'F11', label: 'F11', category: 'function' },
  { value: 'F12', label: 'F12', category: 'function' },

  { value: 'Digit0', label: '0', category: 'number' },
  { value: 'Digit1', label: '1', category: 'number' },
  { value: 'Digit2', label: '2', category: 'number' },
  { value: 'Digit3', label: '3', category: 'number' },
  { value: 'Digit4', label: '4', category: 'number' },
  { value: 'Digit5', label: '5', category: 'number' },
  { value: 'Digit6', label: '6', category: 'number' },
  { value: 'Digit7', label: '7', category: 'number' },
  { value: 'Digit8', label: '8', category: 'number' },
  { value: 'Digit9', label: '9', category: 'number' },

  { value: 'KeyA', label: 'A', category: 'letter' },
  { value: 'KeyB', label: 'B', category: 'letter' },
  { value: 'KeyC', label: 'C', category: 'letter' },
  { value: 'KeyD', label: 'D', category: 'letter' },
  { value: 'KeyE', label: 'E', category: 'letter' },
  { value: 'KeyF', label: 'F', category: 'letter' },
  { value: 'KeyG', label: 'G', category: 'letter' },
  { value: 'KeyH', label: 'H', category: 'letter' },
  { value: 'KeyI', label: 'I', category: 'letter' },
  { value: 'KeyJ', label: 'J', category: 'letter' },
  { value: 'KeyK', label: 'K', category: 'letter' },
  { value: 'KeyL', label: 'L', category: 'letter' },
  { value: 'KeyM', label: 'M', category: 'letter' },
  { value: 'KeyN', label: 'N', category: 'letter' },
  { value: 'KeyO', label: 'O', category: 'letter' },
  { value: 'KeyP', label: 'P', category: 'letter' },
  { value: 'KeyQ', label: 'Q', category: 'letter' },
  { value: 'KeyR', label: 'R', category: 'letter' },
  { value: 'KeyS', label: 'S', category: 'letter' },
  { value: 'KeyT', label: 'T', category: 'letter' },
  { value: 'KeyU', label: 'U', category: 'letter' },
  { value: 'KeyV', label: 'V', category: 'letter' },
  { value: 'KeyW', label: 'W', category: 'letter' },
  { value: 'KeyX', label: 'X', category: 'letter' },
  { value: 'KeyY', label: 'Y', category: 'letter' },
  { value: 'KeyZ', label: 'Z', category: 'letter' },

  { value: 'Numpad0', label: 'Numpad 0', category: 'numpad' },
  { value: 'Numpad1', label: 'Numpad 1', category: 'numpad' },
  { value: 'Numpad2', label: 'Numpad 2', category: 'numpad' },
  { value: 'Numpad3', label: 'Numpad 3', category: 'numpad' },
  { value: 'Numpad4', label: 'Numpad 4', category: 'numpad' },
  { value: 'Numpad5', label: 'Numpad 5', category: 'numpad' },
  { value: 'Numpad6', label: 'Numpad 6', category: 'numpad' },
  { value: 'Numpad7', label: 'Numpad 7', category: 'numpad' },
  { value: 'Numpad8', label: 'Numpad 8', category: 'numpad' },
  { value: 'Numpad9', label: 'Numpad 9', category: 'numpad' },
  { value: 'NumpadEnter', label: 'Numpad Enter', category: 'numpad' },
  { value: 'NumpadAdd', label: 'Numpad +', category: 'numpad' },
  { value: 'NumpadSubtract', label: 'Numpad -', category: 'numpad' },
  { value: 'NumpadMultiply', label: 'Numpad *', category: 'numpad' },
  { value: 'NumpadDivide', label: 'Numpad /', category: 'numpad' },
  { value: 'NumpadDecimal', label: 'Numpad .', category: 'numpad' },
  { value: 'NumpadEqual', label: 'Numpad =', category: 'numpad' },

  { value: 'AudioVolumeMute', label: 'Volume Mute', category: 'media' },
  { value: 'AudioVolumeDown', label: 'Volume Down', category: 'media' },
  { value: 'AudioVolumeUp', label: 'Volume Up', category: 'media' },
  { value: 'MediaPlayPause', label: 'Play/Pause', category: 'media' },
  { value: 'MediaStop', label: 'Stop', category: 'media' },
  { value: 'MediaTrackNext', label: 'Next Track', category: 'media' },
  { value: 'MediaTrackPrevious', label: 'Previous Track', category: 'media' },

  { value: 'Semicolon', label: '; Semicolon', category: 'symbol' },
  { value: 'Equal', label: '= Equal', category: 'symbol' },
  { value: 'Comma', label: ', Comma', category: 'symbol' },
  { value: 'Minus', label: '- Minus', category: 'symbol' },
  { value: 'Period', label: '. Period', category: 'symbol' },
  { value: 'Slash', label: '/ Slash', category: 'symbol' },
  { value: 'Backquote', label: '` Backquote', category: 'symbol' },
  { value: 'BracketLeft', label: '[ Left Bracket', category: 'symbol' },
  { value: 'BracketRight', label: '] Right Bracket', category: 'symbol' },
  { value: 'Backslash', label: '\\ Backslash', category: 'symbol' },
  { value: 'Quote', label: "' Quote", category: 'symbol' },
];

export const KEY_CATEGORY_LABELS: Record<string, string> = {
  function: '功能键',
  navigation: '导航键',
  editing: '编辑键',
  modifier: '修饰键',
  letter: '字母键',
  number: '数字键',
  numpad: '小键盘',
  symbol: '符号键',
  media: '媒体键',
};
