import {
  Play, MousePointer2, MousePointerClick, Type, Keyboard, Scroll, Hand,
  Search, CheckCircle, ToggleLeft,
  Clock, Timer,
  Variable, GitBranch, Repeat, FileText, Flag, StopCircle,
  Image, Move,
} from 'lucide-react';

export type NodeCategory = 'control' | 'ai-action' | 'ai-query' | 'wait' | 'system';

export interface PropertyField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'number' | 'select' | 'switch' | 'variable' | 'key-select' | 'var-name' | 'file-path' | 'image-list' | 'coordinate' | 'key-record' | 'image-template' | 'keyboard-groups';
  description?: string;
  placeholder?: string;
  options?: { label: string; value: string }[];
  defaultValue?: unknown;
  sensitive?: boolean;
  showWhen?: Record<string, string | boolean>;
  multiFile?: boolean;
}

export interface NodeConfig {
  type: string;
  name: string;
  category: NodeCategory;
  icon: React.ComponentType<{ className?: string }>;
  description: string;
  color: string;
  defaultParams: Record<string, unknown>;
  propertyFields: PropertyField[];
}

export const nodeConfigs: NodeConfig[] = [
  // ====== 控制流 ======
  {
    type: 'control.start',
    name: '开始',
    category: 'control',
    icon: Flag,
    description: '工作流的起点，执行从这里开始',
    color: '#22c55e',
    defaultParams: {
      windowMode: 'none',
    },
    propertyFields: [
      {
        key: 'windowMode',
        label: '执行时窗口',
        type: 'select',
        defaultValue: 'none',
        description: '工作流开始执行时主窗口的行为',
        options: [
          { label: '保持不变', value: 'none' },
          { label: '最小化到任务栏', value: 'minimize' },
          { label: '缩小为悬浮小窗', value: 'floating' },
        ],
      },
    ],
  },
  {
    type: 'control.end',
    name: '结束',
    category: 'control',
    icon: StopCircle,
    description: '工作流的终点，执行到这里结束',
    color: '#ef4444',
    defaultParams: {
      message: '',
    },
    propertyFields: [
      { key: 'message', label: '输出内容', type: 'textarea', description: '输入 # 选择变量插入到内容中' },
    ],
  },
  {
    type: 'control.if',
    name: '条件判断',
    category: 'control',
    icon: GitBranch,
    description: '根据条件表达式决定走哪条分支',
    color: '#3b82f6',
    defaultParams: {
      leftVar: '',
      conditionType: 'boolean',
      operator: '==',
      rightValue: true,
    },
    propertyFields: [
      { key: 'leftVar', label: '判断变量', type: 'variable', placeholder: '选择要判断的变量' },
      {
        key: 'conditionType',
        label: '判断类型',
        type: 'select',
        options: [
          { label: '🔢 数字比较', value: 'number' },
          { label: '📝 字符串比较', value: 'string' },
          { label: '✅ 布尔值', value: 'boolean' },
        ],
        defaultValue: 'boolean',
      },
      {
        key: 'operator',
        label: '比较方式',
        type: 'select',
        options: [
          { label: '等于', value: '==' },
          { label: '不等于', value: '!=' },
          { label: '大于', value: '>' },
          { label: '小于', value: '<' },
          { label: '大于等于', value: '>=' },
          { label: '小于等于', value: '<=' },
        ],
        defaultValue: '==',
        showWhen: { conditionType: 'number' },
      },
      {
        key: 'operator',
        label: '比较方式',
        type: 'select',
        options: [
          { label: '等于', value: '==' },
          { label: '不等于', value: '!=' },
          { label: '包含', value: 'contains' },
          { label: '不包含', value: 'notContains' },
          { label: '开头是', value: 'startsWith' },
          { label: '结尾是', value: 'endsWith' },
        ],
        defaultValue: '==',
        showWhen: { conditionType: 'string' },
      },
      {
        key: 'rightValue',
        label: '比较值',
        type: 'text',
        defaultValue: '0',
        description: '数字，输入 # 选择变量',
        showWhen: { conditionType: 'number' },
      },
      {
        key: 'rightValue',
        label: '比较值',
        type: 'text',
        defaultValue: '',
        description: '文字，输入 # 选择变量',
        showWhen: { conditionType: 'string' },
      },
    ],
  },
  {
    type: 'control.loop',
    name: '循环',
    category: 'control',
    icon: Repeat,
    description: '重复执行一段流程，支持 for 计数循环、while 条件循环、forEach 遍历（数组/对象）',
    color: '#f59e0b',
    defaultParams: {
      loopType: 'for',
      from: 1,
      to: 5,
      step: 1,
      iteratorVar: 'i',
      maxIterations: 100,
      condition: '',
      whileLeftVar: '',
      whileConditionType: 'boolean',
      whileOperator: '==',
      whileRightValue: true,
      arrayVar: '',
      itemVar: 'item',
      keyVar: 'key',
      bodyNodeId: '',
    },
    propertyFields: [
      {
        key: 'loopType',
        label: '循环类型',
        type: 'select',
        options: [
          { label: 'for 循环', value: 'for' },
          { label: 'while 循环', value: 'while' },
          { label: 'forEach 遍历', value: 'forEach' },
        ],
        defaultValue: 'for',
      },
      { key: 'from', label: '起始值', type: 'number', defaultValue: 1, showWhen: { loopType: 'for' } },
      { key: 'to', label: '结束值', type: 'number', defaultValue: 5, showWhen: { loopType: 'for' } },
      { key: 'step', label: '步长', type: 'number', defaultValue: 1, showWhen: { loopType: 'for' } },
      { key: 'iteratorVar', label: '迭代变量名', type: 'text', defaultValue: 'i', showWhen: { loopType: 'for' } },
      { key: 'whileLeftVar', label: '判断变量', type: 'variable', placeholder: '选择要判断的变量', showWhen: { loopType: 'while' } },
      {
        key: 'whileConditionType',
        label: '判断类型',
        type: 'select',
        options: [
          { label: '🔢 数字比较', value: 'number' },
          { label: '📝 字符串比较', value: 'string' },
          { label: '✅ 布尔值', value: 'boolean' },
        ],
        defaultValue: 'boolean',
        showWhen: { loopType: 'while' },
      },
      {
        key: 'whileOperator',
        label: '比较方式',
        type: 'select',
        options: [
          { label: '等于', value: '==' },
          { label: '不等于', value: '!=' },
          { label: '大于', value: '>' },
          { label: '小于', value: '<' },
          { label: '大于等于', value: '>=' },
          { label: '小于等于', value: '<=' },
        ],
        defaultValue: '==',
        showWhen: { loopType: 'while', whileConditionType: 'number' },
      },
      {
        key: 'whileOperator',
        label: '比较方式',
        type: 'select',
        options: [
          { label: '等于', value: '==' },
          { label: '不等于', value: '!=' },
          { label: '包含', value: 'contains' },
          { label: '不包含', value: 'notContains' },
          { label: '开头是', value: 'startsWith' },
          { label: '结尾是', value: 'endsWith' },
        ],
        defaultValue: '==',
        showWhen: { loopType: 'while', whileConditionType: 'string' },
      },
      {
        key: 'whileRightValue',
        label: '比较值',
        type: 'text',
        defaultValue: '0',
        description: '数字，输入 # 选择变量',
        showWhen: { loopType: 'while', whileConditionType: 'number' },
      },
      {
        key: 'whileRightValue',
        label: '比较值',
        type: 'text',
        defaultValue: '',
        description: '文字，输入 # 选择变量',
        showWhen: { loopType: 'while', whileConditionType: 'string' },
      },
      { key: 'arrayVar', label: '数据源变量', type: 'variable', placeholder: '选择数组或对象变量', showWhen: { loopType: 'forEach' }, description: '支持数组和 JSON 对象' },
      { key: 'itemVar', label: '当前项变量名', type: 'text', defaultValue: 'item', showWhen: { loopType: 'forEach' }, description: '数组：当前元素；对象：当前值' },
      { key: 'keyVar', label: '键/索引变量名', type: 'text', defaultValue: 'key', showWhen: { loopType: 'forEach' }, description: '数组：索引；对象：键名' },
      { key: 'maxIterations', label: '最大迭代次数', type: 'number', defaultValue: 100, description: '防止死循环的安全限制' },
    ],
  },
  {
    type: 'control.var',
    name: '变量赋值',
    category: 'control',
    icon: Variable,
    description: '创建变量或进行运算，支持中文变量名',
    color: '#8b5cf6',
    defaultParams: {
      varName: '',
      operation: 'set',
      setValueType: 'number',
      value: 0,
      value2: '',
      outputVar: '',
      printResult: false,
      saveToNewVar: false,
      outputVarName: '',
    },
    propertyFields: [
      { key: 'varName', label: '变量名', type: 'var-name', placeholder: '例如: result, count, 计数器' },
      {
        key: 'operation',
        label: '操作类型',
        type: 'select',
        options: [
          { label: '基础赋值', value: '---set---' },
          { label: '赋值 =', value: 'set' },
          { label: '数字运算', value: '---number---' },
          { label: '加法 +', value: 'add' },
          { label: '减法 -', value: 'subtract' },
          { label: '乘法 ×', value: 'multiply' },
          { label: '除法 ÷', value: 'divide' },
          { label: '取余 %', value: 'modulo' },
          { label: '取整', value: 'toInteger' },
          { label: '绝对值', value: 'abs' },
          { label: '四舍五入', value: 'round' },
          { label: '向上取整', value: 'ceil' },
          { label: '向下取整', value: 'floor' },
          { label: '字符串操作', value: '---string---' },
          { label: '字符串拼接', value: 'concat' },
          { label: '截取字符串', value: 'substring' },
          { label: '取第N个字符', value: 'charAt' },
          { label: '替换文本', value: 'replace' },
          { label: '转大写', value: 'toUpperCase' },
          { label: '转小写', value: 'toLowerCase' },
          { label: '去除首尾空格', value: 'trim' },
          { label: '字符串长度', value: 'strLength' },
          { label: '判断包含', value: 'includes' },
          { label: '判断开头', value: 'startsWith' },
          { label: '判断结尾', value: 'endsWith' },
          { label: '数组操作', value: '---array---' },
          { label: '数组长度', value: 'arrayLength' },
          { label: '取第N个元素', value: 'arrayGet' },
          { label: '追加元素', value: 'arrayPush' },
          { label: '弹出最后元素', value: 'arrayPop' },
          { label: '数组转字符串', value: 'arrayJoin' },
          { label: '对象操作', value: '---object---' },
          { label: '获取属性值', value: 'objectGet' },
          { label: '设置属性值', value: 'objectSet' },
          { label: '删除属性', value: 'objectDelete' },
          { label: '获取所有键', value: 'objectKeys' },
          { label: '获取所有值', value: 'objectValues' },
          { label: '类型转换', value: '---convert---' },
          { label: '转字符串', value: 'toString' },
          { label: '转数字', value: 'toNumber' },
        ],
        defaultValue: 'set',
      },
      { key: 'value', label: '值', type: 'number', defaultValue: 1, showWhen: { operation: 'add' } },
      { key: 'value', label: '值', type: 'number', defaultValue: 1, showWhen: { operation: 'subtract' } },
      { key: 'value', label: '值', type: 'number', defaultValue: 1, showWhen: { operation: 'multiply' } },
      { key: 'value', label: '值', type: 'number', defaultValue: 1, showWhen: { operation: 'divide' } },
      { key: 'value', label: '除数', type: 'number', defaultValue: 2, showWhen: { operation: 'modulo' } },
      { key: 'value', label: '起始位置', type: 'number', defaultValue: 0, description: '从0开始', showWhen: { operation: 'substring' } },
      { key: 'value2', label: '结束位置', type: 'number', defaultValue: 5, description: '可选，不填则截取到末尾', showWhen: { operation: 'substring' } },
      { key: 'value', label: '索引位置', type: 'number', defaultValue: 0, description: '从0开始', showWhen: { operation: 'charAt' } },
      { key: 'value', label: '要替换的文本', type: 'text', defaultValue: '', showWhen: { operation: 'replace' } },
      { key: 'value2', label: '替换为', type: 'text', defaultValue: '', showWhen: { operation: 'replace' } },
      { key: 'value', label: '要拼接的文本', type: 'text', defaultValue: '', description: '输入 # 选择变量', showWhen: { operation: 'concat' } },
      { key: 'value', label: '要查找的文本', type: 'text', defaultValue: '', showWhen: { operation: 'includes' } },
      { key: 'value', label: '开头文本', type: 'text', defaultValue: '', showWhen: { operation: 'startsWith' } },
      { key: 'value', label: '结尾文本', type: 'text', defaultValue: '', showWhen: { operation: 'endsWith' } },
      { key: 'value', label: '索引位置', type: 'number', defaultValue: 0, description: '从0开始', showWhen: { operation: 'arrayGet' } },
      { key: 'value2', label: '要追加的元素', type: 'text', defaultValue: '', description: '数字直接写，字符串加引号，输入 # 选择变量', showWhen: { operation: 'arrayPush' } },
      { key: 'outputVar', label: '弹出元素保存到', type: 'text', description: '可选，弹出的元素保存到这个变量', showWhen: { operation: 'arrayPop' } },
      { key: 'value', label: '分隔符', type: 'text', defaultValue: ',', showWhen: { operation: 'arrayJoin' } },
      { key: 'value', label: '属性名', type: 'text', defaultValue: '', description: '支持点路径，如 user.name', showWhen: { operation: 'objectGet' } },
      { key: 'value', label: '属性名', type: 'text', defaultValue: '', description: '支持点路径，如 user.name', showWhen: { operation: 'objectSet' } },
      { key: 'value2', label: '属性值', type: 'text', defaultValue: '', description: '输入 # 选择变量', showWhen: { operation: 'objectSet' } },
      { key: 'value', label: '属性名', type: 'text', defaultValue: '', description: '支持点路径，如 user.name', showWhen: { operation: 'objectDelete' } },
      {
        key: 'setValueType',
        label: '值类型',
        type: 'select',
        options: [
          { label: '数字', value: 'number' },
          { label: '字符串', value: 'string' },
          { label: '布尔值', value: 'boolean' },
          { label: '数组', value: 'array' },
          { label: '对象 (JSON)', value: 'object' },
        ],
        defaultValue: 'number',
        showWhen: { operation: 'set' },
      },
      { key: 'value', label: '值', type: 'number', defaultValue: 0, showWhen: { operation: 'set', setValueType: 'number' } },
      { key: 'value', label: '值', type: 'text', defaultValue: '', description: '输入 # 选择变量', showWhen: { operation: 'set', setValueType: 'string' } },
      { key: 'value', label: '值', type: 'switch', defaultValue: false, showWhen: { operation: 'set', setValueType: 'boolean' } },
      { key: 'value', label: '数组元素', type: 'textarea', defaultValue: '', description: '每行一个元素，数字直接写，文本不用加引号。输入 # 选择变量', showWhen: { operation: 'set', setValueType: 'array' } },
      { key: 'value', label: '对象 (JSON)', type: 'textarea', defaultValue: '{}', description: 'JSON 格式，如 {"name": "张三", "age": 18}', showWhen: { operation: 'set', setValueType: 'object' } },
      { key: 'saveToNewVar', label: '输出到新变量', type: 'switch', defaultValue: false, description: '开启后不修改原变量，结果保存到新变量' },
      { key: 'outputVarName', label: '新变量名', type: 'text', defaultValue: '', description: '默认 return_ 前缀 + 原变量名', showWhen: { saveToNewVar: true } },
      { key: 'printResult', label: '打印返回值', type: 'switch', defaultValue: false, description: '执行后打印变量的当前值到日志' },
    ],
  },
  {
    type: 'control.log',
    name: '日志输出',
    category: 'control',
    icon: FileText,
    description: '打印日志或变量值',
    color: '#8b5cf6',
    defaultParams: {
      message: '',
      level: 'info',
    },
    propertyFields: [
      { key: 'message', label: '日志内容', type: 'textarea', description: '输入 # 选择变量插入到内容中' },
      {
        key: 'level',
        label: '日志级别',
        type: 'select',
        options: [
          { label: '信息 (info)', value: 'info' },
          { label: '警告 (warn)', value: 'warn' },
          { label: '错误 (error)', value: 'error' },
        ],
        defaultValue: 'info',
      },
    ],
  },

  // ====== AI 操作 ======
  {
    type: 'midscene.act',
    name: 'AI 操作',
    category: 'ai-action',
    icon: Play,
    description: 'AI 自动规划并执行复杂操作',
    color: '#06b6d4',
    defaultParams: {
      prompt: '',
      deepThink: false,
      deepLocate: false,
      cacheable: true,
    },
    propertyFields: [
      { key: 'prompt', label: '操作描述', type: 'textarea', placeholder: '例如：打开设置菜单' },
      { key: 'deepThink', label: '深度思考', type: 'switch', description: '引导 AI 注重任务拆解' },
      { key: 'deepLocate', label: '深度定位', type: 'switch', description: '更精准地定位 UI 元素' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
    ],
  },
  {
    type: 'midscene.tap',
    name: '点击元素',
    category: 'ai-action',
    icon: MousePointerClick,
    description: '点击指定的元素，支持文件上传',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      deepLocate: false,
      cacheable: true,
      fileChooserAccept: '',
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：确认按钮' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
      { key: 'fileChooserAccept', label: '上传文件路径', type: 'file-path', description: '点击后触发文件选择器时，要上传的文件路径', multiFile: true },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升定位准确率' },
    ],
  },
  {
    type: 'midscene.doubleClick',
    name: '双击元素',
    category: 'ai-action',
    icon: MousePointer2,
    description: '双击指定的元素',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      deepLocate: false,
      cacheable: true,
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：文件图标' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升定位准确率' },
    ],
  },
  {
    type: 'midscene.rightClick',
    name: '右键元素',
    category: 'ai-action',
    icon: MousePointer2,
    description: '右键点击指定的元素',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      deepLocate: false,
      cacheable: true,
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：文件' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升定位准确率' },
    ],
  },
  {
    type: 'midscene.hover',
    name: '悬停元素',
    category: 'ai-action',
    icon: Hand,
    description: '鼠标悬停在指定元素上',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      deepLocate: false,
      cacheable: true,
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：下拉菜单' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升定位准确率' },
    ],
  },
  {
    type: 'midscene.input',
    name: '输入文本',
    category: 'ai-action',
    icon: Type,
    description: '在指定元素中输入文本',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      value: '',
      deepLocate: false,
      cacheable: true,
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：搜索框' },
      { key: 'value', label: '输入内容', type: 'text' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升定位准确率' },
    ],
  },
  {
    type: 'midscene.clearInput',
    name: '清空输入',
    category: 'ai-action',
    icon: Type,
    description: '清空输入框中的文本',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      deepLocate: false,
      cacheable: true,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：搜索框' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
    ],
  },
  {
    type: 'midscene.keyboardPress',
    name: '按键',
    category: 'ai-action',
    icon: Keyboard,
    description: '在指定元素上按下按键',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      keyName: 'Enter',
      deepLocate: false,
      cacheable: true,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '例如：输入框' },
      { key: 'keyName', label: '按键', type: 'key-select', defaultValue: 'Enter', description: '选择要按下的按键' },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
    ],
  },
  {
    type: 'midscene.scroll',
    name: '滚动',
    category: 'ai-action',
    icon: Scroll,
    description: '滚动页面或指定元素',
    color: '#06b6d4',
    defaultParams: {
      target: '',
      scrollType: 'singleAction',
      direction: 'down',
      distance: 300,
      deepLocate: false,
      cacheable: true,
    },
    propertyFields: [
      { key: 'target', label: '目标描述', type: 'text', placeholder: '留空则滚动页面' },
      {
        key: 'scrollType',
        label: '滚动类型',
        type: 'select',
        options: [
          { label: '单次滚动', value: 'singleAction' },
          { label: '滚动到底部', value: 'scrollToBottom' },
          { label: '滚动到顶部', value: 'scrollToTop' },
        ],
        defaultValue: 'singleAction',
      },
      {
        key: 'direction',
        label: '滚动方向',
        type: 'select',
        options: [
          { label: '向下', value: 'down' },
          { label: '向上', value: 'up' },
          { label: '向左', value: 'left' },
          { label: '向右', value: 'right' },
        ],
        defaultValue: 'down',
      },
      { key: 'distance', label: '滚动距离(px)', type: 'number', defaultValue: 300 },
      { key: 'deepLocate', label: '深度定位', type: 'switch' },
      { key: 'cacheable', label: '启用缓存', type: 'switch', defaultValue: true },
    ],
  },

  // ====== AI 查询 ======
  {
    type: 'midscene.query',
    name: 'AI 查询',
    category: 'ai-query',
    icon: Search,
    description: '让 AI 查询页面内容并返回结构化数据，结果保存为变量供后续节点使用。支持返回数字、字符串、数组、JSON 对象等格式',
    color: '#ec4899',
    defaultParams: {
      prompt: '',
      outputVar: '',
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      {
        key: 'prompt',
        label: '查询描述',
        type: 'textarea',
        placeholder: '例如：获取页面上所有商品的标题和价格，以数组形式返回，每个元素包含 title 和 price 字段',
        description: '请在描述中明确说明你想要的数据格式，如：返回一个数字、返回字符串、返回数组、返回JSON对象（包含哪些字段）等',
      },
      { key: 'outputVar', label: '输出变量名', type: 'text', description: '查询结果保存到这个变量，后续节点可通过 # 引用' },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升识别准确率' },
    ],
  },
  {
    type: 'midscene.assert',
    name: 'AI 断言',
    category: 'ai-query',
    icon: CheckCircle,
    description: '断言页面状态是否符合预期，失败则中断执行并报错',
    color: '#ec4899',
    defaultParams: {
      prompt: '',
      errorMessage: '',
      outputVar: '',
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'prompt', label: '断言描述', type: 'textarea', placeholder: '例如：页面应该显示登录成功' },
      { key: 'errorMessage', label: '失败提示', type: 'text', description: '断言失败时显示的错误信息' },
      { key: 'outputVar', label: '结果变量名', type: 'text', description: '断言结果（true/false）保存到这个变量，可选' },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升判断准确率' },
    ],
  },
  {
    type: 'midscene.boolean',
    name: 'AI 布尔判断',
    category: 'ai-query',
    icon: ToggleLeft,
    description: '让 AI 判断一个条件，返回 true 或 false，结果保存为变量，不中断执行',
    color: '#ec4899',
    defaultParams: {
      prompt: '',
      outputVar: 'result',
      images: [],
      convertHttpImage2Base64: false,
    },
    propertyFields: [
      { key: 'prompt', label: '判断描述', type: 'textarea', placeholder: '例如：页面上是否有登录按钮' },
      { key: 'outputVar', label: '输出变量名', type: 'text', description: '布尔结果保存到这个变量，后续节点可通过 # 引用' },
      { key: 'images', label: '参考图像', type: 'image-list', description: '添加参考图片提升判断准确率' },
    ],
  },

  // ====== 等待 ======
  {
    type: 'midscene.waitFor',
    name: '等待条件',
    category: 'wait',
    icon: Clock,
    description: '等待某个条件满足，超时则失败',
    color: '#10b981',
    defaultParams: {
      prompt: '',
      timeout: 30000,
    },
    propertyFields: [
      { key: 'prompt', label: '等待条件', type: 'text', placeholder: '例如：页面加载完成' },
      { key: 'timeout', label: '超时时间(ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    type: 'control.sleep',
    name: '等待时间',
    category: 'wait',
    icon: Timer,
    description: '等待指定的毫秒数',
    color: '#10b981',
    defaultParams: {
      duration: 1000,
    },
    propertyFields: [
      { key: 'duration', label: '等待时间(ms)', type: 'number', defaultValue: 1000 },
    ],
  },

  // ====== 系统操作 ======
  {
    type: 'system.click',
    name: '左键单击',
    category: 'system',
    icon: MousePointerClick,
    description: '在指定位置单击鼠标左键',
    color: '#8b5cf6',
    defaultParams: {
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      moveDuration: 200,
      onError: 'stop',
    },
    propertyFields: [
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200 },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.doubleClick',
    name: '左键双击',
    category: 'system',
    icon: MousePointer2,
    description: '在指定位置双击鼠标左键',
    color: '#8b5cf6',
    defaultParams: {
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      moveDuration: 200,
      clickInterval: 200,
      onError: 'stop',
    },
    propertyFields: [
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200 },
      { key: 'clickInterval', label: '点击间隔(ms)', type: 'number', defaultValue: 200 },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.rightClick',
    name: '右键单击',
    category: 'system',
    icon: Hand,
    description: '在指定位置单击鼠标右键',
    color: '#8b5cf6',
    defaultParams: {
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      moveDuration: 200,
      onError: 'stop',
    },
    propertyFields: [
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200 },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.hover',
    name: '鼠标悬停',
    category: 'system',
    icon: Move,
    description: '将鼠标移动到指定位置（不点击）',
    color: '#8b5cf6',
    defaultParams: {
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      moveDuration: 200,
      onError: 'stop',
    },
    propertyFields: [
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200 },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.input',
    name: '输入文本',
    category: 'system',
    icon: Type,
    description: '在指定位置输入文本',
    color: '#8b5cf6',
    defaultParams: {
      needLocate: false,
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      value: '',
      moveDuration: 200,
      onError: 'stop',
    },
    propertyFields: [
      { key: 'value', label: '输入内容', type: 'textarea', placeholder: '输入要输入的文本内容' },
      { key: 'needLocate', label: '先定位再输入', type: 'switch', defaultValue: false },
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        showWhen: { needLocate: true },
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { needLocate: true, locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { needLocate: true, locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { needLocate: true, locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200, showWhen: { needLocate: true } },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { needLocate: true, locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.keyboard',
    name: '系统按键',
    category: 'system',
    icon: Keyboard,
    description: '按下系统按键或组合键，支持多组依次执行',
    color: '#8b5cf6',
    defaultParams: {
      keyGroups: [{ keys: [] }],
      groupInterval: 300,
    },
    propertyFields: [
      { key: 'keyGroups', label: '按键组', type: 'keyboard-groups' },
      { key: 'groupInterval', label: '组间间隔(ms)', type: 'number', defaultValue: 300 },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.scroll',
    name: '滚轮滑动',
    category: 'system',
    icon: Scroll,
    description: '滚动鼠标滚轮',
    color: '#8b5cf6',
    defaultParams: {
      needLocate: false,
      locateMode: 'coordinate',
      x: 0,
      y: 0,
      templateImage: '',
      confidence: 0.9,
      direction: 'down',
      amount: 3,
      moveDuration: 200,
      onError: 'stop',
    },
    propertyFields: [
      {
        key: 'direction',
        label: '滚动方向',
        type: 'select',
        defaultValue: 'down',
        options: [
          { label: '向上', value: 'up' },
          { label: '向下', value: 'down' },
          { label: '向左', value: 'left' },
          { label: '向右', value: 'right' },
        ],
      },
      { key: 'amount', label: '滚动格数', type: 'number', defaultValue: 3 },
      { key: 'needLocate', label: '先定位再滚动', type: 'switch', defaultValue: false },
      {
        key: 'locateMode',
        label: '定位方式',
        type: 'select',
        defaultValue: 'coordinate',
        showWhen: { needLocate: true },
        options: [
          { label: '坐标定位', value: 'coordinate' },
          { label: '图片匹配', value: 'image' },
        ],
      },
      { key: 'coordinate', label: '目标坐标', type: 'coordinate', showWhen: { needLocate: true, locateMode: 'coordinate' } },
      { key: 'templateImage', label: '模板图片', type: 'image-template', showWhen: { needLocate: true, locateMode: 'image' } },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9, showWhen: { needLocate: true, locateMode: 'image' } },
      { key: 'moveDuration', label: '移动时长(ms)', type: 'number', defaultValue: 200, showWhen: { needLocate: true } },
      {
        key: 'onError',
        label: '失败策略',
        type: 'select',
        defaultValue: 'stop',
        options: [
          { label: '停止流程', value: 'stop' },
          { label: '继续执行', value: 'continue' },
        ],
        showWhen: { needLocate: true, locateMode: 'image' },
      },
      { key: 'postDelay', label: '结束后等待(ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    type: 'system.waitForImage',
    name: '图片条件等待',
    category: 'wait',
    icon: Image,
    description: '等待图片出现，匹配到走true分支，超时走false分支',
    color: '#f59e0b',
    defaultParams: {
      templateImage: '',
      confidence: 0.9,
      timeout: 30000,
      checkInterval: 500,
    },
    propertyFields: [
      { key: 'templateImage', label: '模板图片', type: 'image-template' },
      { key: 'confidence', label: '匹配置信度', type: 'number', defaultValue: 0.9 },
      { key: 'timeout', label: '超时时间(ms)', type: 'number', defaultValue: 30000 },
      { key: 'checkInterval', label: '检测间隔(ms)', type: 'number', defaultValue: 500 },
    ],
  },
];

export const categoryLabels: Record<NodeCategory, string> = {
  control: '控制流',
  'ai-action': 'AI 操作',
  'ai-query': 'AI 查询',
  wait: '等待',
  system: '系统操作',
};

export const getNodeConfig = (type: string): NodeConfig | undefined => {
  return nodeConfigs.find((c) => c.type === type);
};
